### ISSUE TITLE
啥时候整个激励视频啊

### ISSUE THREAD

**Issue by zhangruiyu** [OpenFlutter/Pangolin#1]
啥时候整个激励视频啊

**Comment by tongyangsheng** [comment]
激励视频清明应该就可以搞定了

**Comment by tongyangsheng** [comment]
激励视频已在版本内 请查阅

**Comment by zhangruiyu** [comment]
反手给你一个感谢的抱抱

**Comment by zhangruiyu** [comment]
激励视频 能给个参数吗 比如userid和附加参数的 我这边原生是用到了

**Comment by tongyangsheng** [comment]
你是说和服务器配合的那种激励视频吗

**Comment by zhangruiyu** [comment]
是的  因为后台做校验肯定是更安全 防止别人刷单  目前我们就采用后台校验的方式这个搞的 传入userid和token 还有关键字参数 后台去校验

**Comment by tongyangsheng** [comment]
主要是我们这边 没有这个需求 服务端没搞我这边不好测 你有Mock数据或者 接口吗

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/79098675-125e7200-7d95-11ea-9dcf-6c517c82f977.png)
主要是添加参数就好 后台我都做完了 而且也测了 就是要传入参数

**Comment by nnianhouss** [comment]
有不有腾讯优量汇广告的Flutter插件呀，楼主考虑写一个吗

**Comment by tongyangsheng** [comment]
@nnianhou- 广告SDK大同小异 你们产品经理不死脑筋的话 你可以推荐他穿山甲 其实收益上不会差很多 我们之前想用百度的百青藤 后来我推荐了他们用了穿山甲

**Comment by tongyangsheng** [comment]
@zhangruiyu 只需要在请求adslot 里添加两个参数就OK吗 这样的话 看起来不是很难
