### ISSUE TITLE
ios 报错

### ISSUE THREAD

**Issue by ruifly2012** [OpenFlutter/Pangolin#11]
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/zr/lvxingcat/lvxingcat_client/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework and /Users/zr/lvxingcat/lvxingcat_client/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUFoundation.framework)

**Comment by tongyangsheng** [comment]
请提供使用的Pangolin版本号 有一个类似bug在最新版本中以及修复了

**Comment by githubzhaoqian** [comment]
- SDK information
  - Version Number: 3.0.0.2
  - Updated: 2020-06-07
  - Change Log:
    - Optimization splash ad 
      - Improve the filling ability of  splash ads
      - Support video splash ad
    - Optimized playable ads，Improve the filling ability and playback fluency


还需要其他信息吗 应该是穿山甲sdk的问题   pod install 就会提示这个错误

**Comment by githubzhaoqian** [comment]
- Running pre install hooks
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/name/Desktop/flu/fl/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework and /Users/name/Desktop/flu/fl/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUFoundation.framework)

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by tongyangsheng** [comment]
升级到1.0.4
