### ISSUE TITLE
debug 参数失效

### ISSUE THREAD

**Issue by huahaomei521** [OpenFlutter/Pangolin#12]
debug 参数修改不起作用，测试环境：debug模式和release模式，穿山甲测试模式，RewardAd
dart里面设置了false，还是会弹窗各阶段信息

0.1.1

即使改成本地插件，修改里面内容，也是不生效。。。

是我改得地方改错了，改了RewardVideoActivity。。。。

**Comment by tongyangsheng** [comment]
好 我稍后会确认相关问题 应该是参数传递过程中遗漏了，下个版本中会修复，希望你提供一下使用的广告 开屏还是激励

**Comment by tongyangsheng** [comment]
debug参数失效问题已修复
