### ISSUE TITLE
ios pod install 错误

### ISSUE THREAD

**Issue by gaoyong06** [OpenFlutter/Pangolin#13]
在xcode里面按照下面的
[https://partner.oceanengine.com/union/media/union/download/detail?id=16&docId=5de8d570b1afac00129330c5&osType=ios](url)
配置了“Xcode编译选项设置”

然后在pubspec.yaml 里面添加了:
pangolin: ^0.1.1

然后在 项目的ios目录执行:
pod install

就报下面的错误：

`

    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/name/Documents/work/app/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUAdSDK.framework and
    /Users/name/Documents/work/app/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks/BUFoundation.framework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

`

翻了一下，有过一个类似的issues 不过没有结论[https://github.com/OpenFlutter/Pangolin/issues/11](url)
新开一个，把情况描述一下

**Comment by tongyangsheng** [comment]
请确认cocoapods是否使用国内镜像源，如果有请移除

**Comment by gaoyong06** [comment]
> 请确认cocoapods是否使用国内镜像源，如果有请移除

最后在ios/Podfile 添加


    pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end


解决了
 [参考文档](https://github.com/flutter/flutter/issues/20045)
