### ISSUE TITLE
ios build出现错误

### ISSUE THREAD

**Issue by gaoyong06** [OpenFlutter/Pangolin#15]
执行 pod install 没问题
flutter run 
或者在xcode里面build的时候，就报下面的错误

Ld /Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Products/Debug-iphoneos/pangolin/pangolin.framework/pangolin normal arm64 (in target 'pangolin' from project 'Pods')
    cd /Users/name/Documents/work/app/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios9.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk -L/Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Products/Debug-iphoneos/pangolin -F/Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Products/Debug-iphoneos/pangolin -F/Users/name/Documents/work/app/ios/Pods/../Flutter -F/Users/name/Documents/work/app/ios/Pods/Bytedance-UnionAD/Bytedance-UnionAd/Frameworks -filelist /Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/pangolin.build/Objects-normal/arm64/pangolin.LinkFileList -install_name @rpath/pangolin.framework/pangolin -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/pangolin.build/Objects-normal/arm64/pangolin_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -framework AVFoundation -framework Accelerate -framework AdSupport -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreTelephony -framework Flutter -framework MapKit -framework MediaPlayer -framework MobileCoreServices -framework StoreKit -framework SystemConfiguration -framework UIKit -framework WebKit -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/pangolin.build/Objects-normal/arm64/pangolin_dependency_info.dat -o /Users/name/Library/Developer/Xcode/DerivedData/Runner-hgtradzyhdbyjrgskseiaroegqwf/Build/Products/Debug-iphoneos/pangolin/pangolin.framework/pangolin

Undefined symbols for architecture arm64:
  "_kBU_voice_silent", referenced from:
      -[BUNativeExpressRewardedVideoAdViewController silentButton] in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      -[BUNativeExpressRewardedVideoAdViewController silentButtonTapped:] in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      -[BURewardedVideoAdViewController silentButtonTapped:] in BUAdSDK(BURewardedVideoAdViewController.o)
      -[BURewardedVideoAdViewController silentButton] in BUAdSDK(BURewardedVideoAdViewController.o)
      -[BURewardedVideoTopBarView updateSilentButtonStatus:] in BUAdSDK(BURewardedVideoTopBarView.o)
  "_kBU_nextCell", referenced from:
      -[BUDislikeTableViewCell initWithStyle:reuseIdentifier:] in BUAdSDK(BUDislikeTableViewCell.o)
  "_OBJC_CLASS_$_BUThreadSafeDictionary", referenced from:
      objc-class-ref in BUAdSDK(BUAdViewWitnessChecker.o)
      objc-class-ref in BUAdSDK(BUDynamicLayoutService.o)
      objc-class-ref in BUAdSDK(BUUSettingService.o)
      objc-class-ref in BUAdSDK(BUTrackerProxy.o)
  "_OBJC_CLASS_$_BUWebViewProgressView", referenced from:
      objc-class-ref in BUAdSDK(BUWebViewController.o)
  "_OBJC_METACLASS_$_BUWKWebView", referenced from:
      _OBJC_METACLASS_$_BUWKWebViewClient in BUAdSDK(BUWKWebViewClient.o)
     (maybe you meant: _OBJC_METACLASS_$_BUWKWebViewClient)
  "_kBU_logoAd_oversea", referenced from:
      -[BUExpressCoverView logoImageView] in BUAdSDK(BUExpressCoverView.o)
  "_OBJC_CLASS_$_BUWebViewApplication", referenced from:
      objc-class-ref in BUAdSDK(BURewardedVideoWebViewController.o)
      objc-class-ref in BUAdSDK(BUAppStoreDisplayInAppViewController.o)
      objc-class-ref in BUAdSDK(BUWebViewController.o)
  "_OBJC_CLASS_$_BUCocoaSecurity", referenced from:
      objc-class-ref in BUAdSDK(BUNetworkSecurity.o)
  "_OBJC_CLASS_$_BUCocoaSecurityDecoder", referenced from:
      objc-class-ref in BUAdSDK(BUNetworkSecurity.o)
  "_kBU_fastBackward", referenced from:
      -[BU_ZFPlayerControlView buzf_playerDraggedTime:totalTime:isForward:hasPreview:] in BUAdSDK(BU_ZFPlayerControlView.o)
  "_kBUReachabilityChangedNotification", referenced from:
      -[BUNativeExpressAdView addReachabilityNotification] in BUAdSDK(BUNativeExpressAdView.o)
      ___32-[BURewardedVideoPreloader init]_block_invoke in BUAdSDK(BURewardedVideoPreloader.o)
      -[BUVideoAdView initWithMaterial:] in BUAdSDK(BUVideoAdView.o)
  "_OBJC_CLASS_$_BUNetInfoHelper", referenced from:
      objc-class-ref in BUAdSDK(BUAdEventTracker.o)
      objc-class-ref in BUAdSDK(BUAppStoreManager.o)
      objc-class-ref in BUAdSDK(BUDevice.o)
      objc-class-ref in BUAdSDK(BUURLTracker.o)
      objc-class-ref in BUAdSDK(BUNetworkRequest.o)
      objc-class-ref in BUAdSDK(BUNativeExpressFeedVideoAdView.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloader.o)
      ...
  "_OBJC_CLASS_$_BUDeviceHelper", referenced from:
      objc-class-ref in BUAdSDK(BUAppStoreManager.o)
      objc-class-ref in BUAdSDK(BUDevice.o)
      objc-class-ref in BUAdSDK(BUUSettingService.o)
      objc-class-ref in BUAdSDK(BUAPIClinet.o)
      objc-class-ref in BUAdSDK(BUAppStorePreloadItem.o)
      objc-class-ref in BUAdSDK(BURewardedVideoWebViewController.o)
      objc-class-ref in BUAdSDK(BUTrackerProxy.o)
      ...
  "_OBJC_CLASS_$_BU_SDWebImageManager", referenced from:
      objc-class-ref in BUAdSDK(BUNativeExpressAdManager.o)
      objc-class-ref in BUAdSDK(BUSplashPreloader.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloaderManager.o)
      objc-class-ref in BUAdSDK(BUURLProtocol.o)
      objc-class-ref in BUAdSDK(BUWKWebViewClient.o)
  "_OBJC_METACLASS_$_BUBaseRequest", referenced from:
      _OBJC_METACLASS_$_BUNetworkRequest in BUAdSDK(BUNetworkRequest.o)
  "_OBJC_CLASS_$_BUFoundationAddress", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_OBJC_CLASS_$_HMDBUToBAddressRange", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_kBU_playableLoading", referenced from:
      -[BUPurePlayableLoadingViewController viewDidLoad] in BUAdSDK(BUPurePlayableLoadingViewController.o)
  "_OBJC_CLASS_$_EBAppLog", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_OBJC_CLASS_$_EBAppLogConfig", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_kBU_logoAd", referenced from:
      -[BUExpressCoverView logoImageView] in BUAdSDK(BUExpressCoverView.o)
  "_OBJC_CLASS_$_BUScreenHelper", referenced from:
      objc-class-ref in BUAdSDK(BUAppStorePreloadItem.o)
      objc-class-ref in BUAdSDK(BUTrackerProxy.o)
      objc-class-ref in BUAdSDK(BU_ZFPlayerControlView.o)
  "_kBU_fullClose", referenced from:
      -[BUExpressCoverView buildBannerSmallView] in BUAdSDK(BUExpressCoverView.o)
      -[BU_ZFPlayerControlView setOrientationPortraitConstraint] in BUAdSDK(BU_ZFPlayerControlView.o)
  "_kBU_close", referenced from:
      -[BUWebViewController creatNavigationItems] in BUAdSDK(BUWebViewController.o)
  "_OBJC_CLASS_$_HMDBUToBCrashTrackerRestrict", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_OBJC_CLASS_$_BURouter", referenced from:
      objc-class-ref in BUAdSDK(BUAWebPageActionManager.o)
      objc-class-ref in BUAdSDK(BUAdDeepLinkActionManager.o)
      objc-class-ref in BUAdSDK(BUVideoAdActionManager.o)
  "_BU_JSONObjectByRemovingKeysWithNullValues", referenced from:
      ___33-[BUUSettingService fetchSetting]_block_invoke.139 in BUAdSDK(BUUSettingService.o)
  "_OBJC_CLASS_$_BUInfoHelper", referenced from:
      objc-class-ref in BUAdSDK(BUTNCNetwork.o)
      objc-class-ref in BUAdSDK(BUUSettingService.o)
      objc-class-ref in BUAdSDK(BUByteFinder.o)
      objc-class-ref in BUAdSDK(BUTrackerProxy.o)
      objc-class-ref in BUAdSDK(BUApp.o)
  "_OBJC_CLASS_$_BURuntimeUtil", referenced from:
      objc-class-ref in BUAdSDK(BUWKWebViewClient.o)
  "_kBU_endCardClose", referenced from:
      -[BUNativeExpressRewardedVideoAdViewController closeButton] in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      -[BURewardedVideoAdViewController closeButton] in BUAdSDK(BURewardedVideoAdViewController.o)
      -[BURewardedVideoWebViewController closeButton] in BUAdSDK(BURewardedVideoWebViewController.o)
  "_kBU_dislike", referenced from:
      -[BUExpressCoverView dislikeButton] in BUAdSDK(BUExpressCoverView.o)
  "_OBJC_CLASS_$_BUReachability", referenced from:
      objc-class-ref in BUAdSDK(BUNativeExpressFeedVideoAdView.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloader.o)
      objc-class-ref in BUAdSDK(BUVideoAdView.o)
  "_OBJC_CLASS_$_BUWKWebView", referenced from:
      objc-class-ref in BUAdSDK(BUGDPRViewController.o)
      _OBJC_CLASS_$_BUWKWebViewClient in BUAdSDK(BUWKWebViewClient.o)
     (maybe you meant: _OBJC_CLASS_$_BUWKWebViewClient)
  "_OBJC_CLASS_$_BUTimer", referenced from:
      objc-class-ref in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      objc-class-ref in BUAdSDK(BURewardedVideoAdViewController.o)
      objc-class-ref in BUAdSDK(BUNativeExpressAdView.o)
      objc-class-ref in BUAdSDK(BUNativeExpressFeedVideoAdView.o)
      objc-class-ref in BUAdSDK(BUNativeExpressRewardedVideoAdView.o)
      objc-class-ref in BUAdSDK(BUNativeExpressSplashVideoAdView.o)
      objc-class-ref in BUAdSDK(BURewardedVideoDisplayViewController.o)
      ...
  "_OBJC_CLASS_$_BUGifImageView", referenced from:
      objc-class-ref in BUAdSDK(BUSplashAdView.o)
  "_BU_LOG_ENABLED", referenced from:
      +[BUAdSDKManager setAppID:] in BUAdSDK(BUAdSDKManager.o)
      +[BUAdSDKManager setLoglevel:] in BUAdSDK(BUAdSDKManager.o)
      -[BUNativeExpressRewardedVideoAd initWithSlotID:rewardedVideoModel:] in BUAdSDK(BUNativeExpressRewardedVideoAd.o)
      -[BUSplashAdView initWithSlotID:frame:] in BUAdSDK(BUSplashAdView.o)
      ___38-[BUSplashAdView updateViewWithModel:]_block_invoke in BUAdSDK(BUSplashAdView.o)
      +[BUAdEventTracker trackWithTag:label:value:logExtra:extraDic:] in BUAdSDK(BUAdEventTracker.o)
      +[BUCacheControl crashMessageSend:] in BUAdSDK(BUCacheControl.o)
      ...
  "_kBU_GDPRBack", referenced from:
      -[BUGDPRViewController buildupView] in BUAdSDK(BUGDPRViewController.o)
  "_OBJC_CLASS_$_BUPersistenceOption", referenced from:
      objc-class-ref in BUAdSDK(BUDynamicLayoutService.o)
      objc-class-ref in BUAdSDK(BUSplashPreloader.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloaderManager.o)
  "_OBJC_CLASS_$_BUThreadSafeMutableArray", referenced from:
      objc-class-ref in BUAdSDK(BUDynamicLayoutService.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloader.o)
      objc-class-ref in BUAdSDK(BUResourceLoader.o)
  "_OBJC_CLASS_$_HMDBUToBCrashTracker", referenced from:
      objc-class-ref in BUAdSDK(BUByteFinder.o)
  "_kBU_fastForward", referenced from:
      -[BU_ZFPlayerControlView buzf_playerDraggedTime:totalTime:isForward:hasPreview:] in BUAdSDK(BU_ZFPlayerControlView.o)
  "_bu_safe_dispatch_async_main_queue", referenced from:
      -[BUDynamicLayoutService updateTemplateURL:loadingStatus:] in BUAdSDK(BUDynamicLayoutService.o)
      ___54-[BUDynamicLayoutService saveNewTemplate:templateUrl:]_block_invoke_2 in BUAdSDK(BUDynamicLayoutService.o)
      ___66-[BUDynamicLayoutService fetchDynamicLayoutTemplateWithDCChanged:]_block_invoke_2 in BUAdSDK(BUDynamicLayoutService.o)
      -[BUDynamicLayoutService fetchDynamicLayoutTemplateDataWithTempId:URL:md5:successGetTemplateData:] in BUAdSDK(BUDynamicLayoutService.o)
      -[BUAPIClient fetchNativeAdsJsonWithAdSlot:reqType:slotParams:completionHandler:] in BUAdSDK(BUAPIClinet.o)
      ___81-[BUAPIClient fetchNativeAdsJsonWithAdSlot:reqType:slotParams:completionHandler:]_block_invoke_2 in BUAdSDK(BUAPIClinet.o)
      ___81-[BUAPIClient fetchNativeAdsJsonWithAdSlot:reqType:slotParams:completionHandler:]_block_invoke.293 in BUAdSDK(BUAPIClinet.o)
      ...
  "_OBJC_CLASS_$_BUPersistence", referenced from:
      objc-class-ref in BUAdSDK(BUDynamicLayoutService.o)
      objc-class-ref in BUAdSDK(BUSplashPreloader.o)
      objc-class-ref in BUAdSDK(BUURLTracker.o)
      objc-class-ref in BUAdSDK(BURewardedVideoPreloaderManager.o)
      objc-class-ref in BUAdSDK(BUTrackerStorage.o)
  "_kBU_voice", referenced from:
      -[BUNativeExpressRewardedVideoAdViewController silentButton] in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      -[BUNativeExpressRewardedVideoAdViewController silentButtonTapped:] in BUAdSDK(BUNativeExpressRewardedVideoAdViewController.o)
      -[BURewardedVideoAdViewController silentButtonTapped:] in BUAdSDK(BURewardedVideoAdViewController.o)
      -[BURewardedVideoAdViewController silentButton] in BUAdSDK(BURewardedVideoAdViewController.o)
      -[BURewardedVideoTopBarView silentButton] in BUAdSDK(BURewardedVideoTopBarView.o)
      -[BURewardedVideoTopBarView updateSilentButtonStatus:] in BUAdSDK(BURewardedVideoTopBarView.o)
  "_BUSDKVersion", referenced from:
      +[BUAdSDKManager setAppID:] in BUAdSDK(BUAdSDKManager.o)
      +[BUAdSDKManager SDKVersion] in BUAdSDK(BUAdSDKManager.o)
      -[BUNativeExpressRewardedVideoAd initWithSlotID:rewardedVideoModel:] in BUAdSDK(BUNativeExpressRewardedVideoAd.o)
      -[BUSplashAdView initWithSlotID:frame:] in BUAdSDK(BUSplashAdView.o)
      ___38-[BUSplashAdView updateViewWithModel:]_block_invoke in BUAdSDK(BUSplashAdView.o)
      +[BUAdEventTracker trackWithTag:label:value:logExtra:extraDic:] in BUAdSDK(BUAdEventTracker.o)
      +[BUCacheControl crashMessageSend:] in BUAdSDK(BUCacheControl.o)
      ...
  "_OBJC_CLASS_$_BUBaseRequest", referenced from:
      _OBJC_CLASS_$_BUNetworkRequest in BUAdSDK(BUNetworkRequest.o)
  "_OBJC_CLASS_$_BUUIResponderHelper", referenced from:
      objc-class-ref in BUAdSDK(BUSplashAdView.o)
      objc-class-ref in BUAdSDK(BUNativeAd.o)
      objc-class-ref in BUAdSDK(BUNativeExpressAdView.o)
      objc-class-ref in BUAdSDK(BUViewTrackerHelper.o)
      objc-class-ref in BUAdSDK(BU_ZFPlayerView.o)
  "_OBJC_CLASS_$_BUTLocationService", referenced from:
      objc-class-ref in BUAdSDK(BUAdSDKManager.o)
      objc-class-ref in BUAdSDK(BUUSettingService.o)
      objc-class-ref in BUAdSDK(BURewardedVideoRequestModel.o)
      objc-class-ref in BUAdSDK(BUApp.o)
      objc-class-ref in BUAdSDK(BUDislikeRequestManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tongyangsheng** [comment]
升级到1.0.4
