### ISSUE TITLE
android release包异常

### ISSUE THREAD

**Issue by gstory0404** [OpenFlutter/Pangolin#16]
打出release.包以后 发现激励广告 无法打开 查看日志也没有提示异常

**Comment by gstory0404** [comment]
debug包 是正常的显示，但是debug 参数都是无效的  true false都是一直弹toast

**Comment by tongyangsheng** [comment]
release包的问题已经在错误文档里写出方案了

**Comment by tongyangsheng** [comment]
debug参数无效也已修复
