### ISSUE TITLE
开屏广告使用失效

### ISSUE THREAD

**Issue by FangPro** [OpenFlutter/Pangolin#2]
兄弟，你这插件我看了源码。你这不是flutter插件吗，你在android端加载开屏广告时返回View给flutter了吗，只返回个bool值，你怎么展示你的开屏广告？

**Comment by tongyangsheng** [comment]
Flutter插件的本质就是原生调用，为啥要返回一个View给Flutter 直接Android显示出一个Activity iOS显示一个ViewController就行了 bool是调用方法是否成功的回调  回调一个View太可怕了

**Comment by FangPro** [comment]
谢谢你的提醒，Android端代码混淆的问题，已解决。我这边接入的sdk是采用androidView的方式直接嵌套直接flutter端，所以就在android代码里需要把获取的广告view添加到一个framelayout中，再将这个framelayout通过PlatformView的方式返回给flutter。再在广告点击的回调方法里，比如“跳过”， 去实现flutter端事件控制广告跳转的方法。对了，你的插件我用了。但是总是报找不到广告sdk的错误，这个原生sdk是需要开发人员自己配置吗，还是你在插件里配置好了。总之，还是分的感谢你，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "多肉葡萄"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上6:07
收件人: "tongyangsheng/Pangolin"<Pangolin@noreply.github.com&gt;; 
抄送: "方文涛"<1504326556@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [tongyangsheng/Pangolin] 开屏广告使用失效 (#2)





 
Flutter插件的本质就是原生调用，为啥要返回一个View给Flutter 直接Android显示出一个Activity iOS显示一个ViewController就行了 bool是调用方法是否成功的回调  回调一个View太可怕了

**Comment by tongyangsheng** [comment]
在集成过程中需要自己导入所需的SDK 看你的问题应该是Android端吧 因为穿山甲本身不支持implementation的方式集成，所以需要自己导入一个SDK 很简单的步骤 既然你提了我稍后会在文档内更新相关内容 注意查看

**Comment by FangPro** [comment]
好的，我会持续关注的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "多肉葡萄"<notifications@github.com&gt;; 
发送时间: 2020年4月8日(星期三) 上午10:10
收件人: "tongyangsheng/Pangolin"<Pangolin@noreply.github.com&gt;; 
抄送: "方文涛"<1504326556@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [tongyangsheng/Pangolin] 开屏广告使用失效 (#2)





 
在集成过程中需要自己导入所需的SDK 看你的问题应该是Android端吧 因为穿山甲本身不支持implementation的方式集成，所以需要自己导入一个SDK 很简单的步骤 既然你提了我稍后会在文档内更新相关内容 注意查看
