### ISSUE TITLE
开屏广告加载失败。

### ISSUE THREAD

**Issue by wengxianxun** [OpenFlutter/Pangolin#21]
D/splashLoad(12335): 广告物料预加载失败....服务异常40033
D/SplashAdCacheManager(12335): 服务异常40033
E/SplashAdCacheManager(12335): SplashAdCacheManager 已经加载过了 adSlot.getCodeId() 887343401
E/SplashAdCacheManager(12335): SplashAdCacheManager 是否需要加载其他rit开屏广告
E/SplashAdCacheManager(12335): mloadSplashParaHashMap == null || mloadSplashParaHashMap.size() == 0

**Comment by tongyangsheng** [comment]
官网解决方案如下：

解决方案：在预加载时，增加日志输出穿山甲错误码和错误原因，或者去穿山甲集成文档查询对于的错误原因。

常见的错误是：

APPID和广告位ID不匹配，如：用A APP，设置的是B APP的广告位ID；
广告接口设置错误的广告位ID，如：激励视频接口设置的是插屏广告位ID；
广告位ID复制粘贴错误；
40029，最近最常见的，需要升级穿山甲最新版本才能使用。
debug版本没签名或不对，导致无法展示广告。
