### ISSUE TITLE
插屏广告找不到方法

### ISSUE THREAD

**Issue by wengxianxun** [OpenFlutter/Pangolin#26]
Unhandled Exception: MissingPluginException(No implementation found for method loadInterstitialAd on channel com.tongyangsheng.pangolin)

**Comment by wengxianxun** [comment]
插屏是不是还没做完啊，我看了源码也没有找到

**Comment by tongyangsheng** [comment]
我写了只支持iOS啊

**Comment by wengxianxun** [comment]
为什么不支持安卓呢？
