### ISSUE TITLE
开屏广告使用失效

### ISSUE THREAD

**Issue by FangPro** [OpenFlutter/Pangolin#3]
大佬你好，我在实际接入穿山甲广告sdk过程中使用的是调用sdk+返回PlatformView的方法。测试是直接运行debug全能展示的，但是我打成release包过后广告就没了，我测试了一下在打成release包后，调用开屏广告里的方法 "mTTAdNative.loadSplashAd(adSlot, new TTAdNative.SplashAdListener() {...}"就不执行了，在直接运行debug模式时是完全正常的，但是打包成release就是没有，不知道你在实际开发过程中是否遇到，是怎样解决的，谢谢。

**Comment by tongyangsheng** [comment]
你是使用Pangolin的接口吗 还是自己集成的？

**Comment by FangPro** [comment]
你好，我是自己集成的，我就是想了解一下你有没有不通过插件的方式直接将sdk接入到android模块，然后打包成release版本广告不显示， 谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "多肉葡萄"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 下午5:33
收件人: "tongyangsheng/Pangolin"<Pangolin@noreply.github.com&gt;; 
抄送: "方文涛"<1504326556@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tongyangsheng/Pangolin] 开屏广告使用失效 (#3)





 
你是使用Pangolin的接口吗 还是自己集成的？

**Comment by tongyangsheng** [comment]
我没有遇到类似问题，我自己的项目中也进行了打包测试，开屏没有问题，根据你的描述可能的问题应该有：
1.如果打成release包 确认代码中的混淆的问题
2.如果是方法不调用确认穿山甲SDK初始化是否成功以及用户权限授权状态是否正常
3.确认你的方法在主线程回调，并确保主线程没有被UI操作阻塞
4.将debug参数调致false
5.检查穿山甲控制台对应代码位是否有相应的请求记录
6.检查真机网络状态

**Comment by tongyangsheng** [comment]
fixed #2
