### ISSUE TITLE
监听回调 value.rewardVerify = false

### ISSUE THREAD

**Issue by Songzongyu** [OpenFlutter/Pangolin#31]
视频观看结束, 回调值value.rewardVerify = false  之前结束都是true, 现在是false.

**Comment by tongyangsheng** [comment]
请提供 更多信息 Pangolin版本，操作系统

**Comment by tongyangsheng** [comment]
本自测多种情况下监听正常，有其他人发现该问题或者自己确认后还存在问题可以重开。先关了
