### ISSUE TITLE
iOS 无法打开激励视频 画面

### ISSUE THREAD

**Issue by Songzongyu** [OpenFlutter/Pangolin#32]
初始化成功, 点击观看视频Pangolin.loadRewardAd(...).then((value) { 这里返回的是成功的! })  但是不弹出视频!

**Comment by tongyangsheng** [comment]
请提供必要信息，参照issue格式，谢谢

**Comment by Songzongyu** [comment]
初始化成功, 点击观看视频Pangolin.loadRewardAd(...).then((value) { 这里返回的是成功的! }) 但是不弹出视频!

格式
激励视频无法打开
Pangolin v0.2.2
Flutter 1.18.0-11.1.pre
ios
必现
