### ISSUE TITLE
iOS无法打开激励视频画面

### ISSUE THREAD

**Issue by Songzongyu** [OpenFlutter/Pangolin#34]
初始化成功，点击观看视频Pangolin.loadRewardAd（...）。then（（value）{这里返回的是成功的！}）但是不切换视频！

格式
激励视频无法打开
Pangolin v0.2.2
Flutter 1.18.0-11.1.pre
ios
必现

**Comment by tongyangsheng** [comment]
Flutter stable 版本没有 1.18.0吧。。。

**Comment by tongyangsheng** [comment]
建议你先用我 example里的iOS demo跑一下 没问题的话再做进一步排查 有问题的话建议切到stable版本，目前我这边检查了没有问题，没有收到打不开激励视频的反馈
