### ISSUE TITLE
广告覆盖问题

### ISSUE THREAD

**Issue by CodeGather** [OpenFlutter/Pangolin#37]
使用banner在一个界面显示后，pageview 切换时 在另外一个界面还是会显示

是否是每次页面销毁是主动去关闭banner广告

**Comment by CodeGather** [comment]
还有一个问题就是开屏广告没有回调

**Comment by tongyangsheng** [comment]
第一个问题：yes，注意看文档，针对这个问题已经提供了手动关闭的方法🤪

**Comment by CodeGather** [comment]
> 第一个问题：yes，注意看文档，针对这个问题已经提供了手动关闭的方法🤪

那第二个问题呢，我是有一个空白页是用来加载广告，现在需要知道倒计时结束后重新跳转页面

**Comment by CodeGather** [comment]
自己动手，已完成，关闭issue
