### ISSUE TITLE
ios中如何关闭banner广告

### ISSUE THREAD

**Issue by bigtotorouk** [OpenFlutter/Pangolin#38]
我看到文档中有android的方式关闭banner广告。ios和 。目前ios切换界面的banner的时候，banner不会消失。

**Comment by tongyangsheng** [comment]
iOS不会关闭吗？之前用户反馈的是会关闭的呀，我有空看一下吧

**Comment by bigtotorouk** [comment]
@tongyangsheng 不是用户关闭 。 比如我一个界面打开的时候，会显示这个banner广告 。 当我关闭这个界面的时候，这个banner没有自动关闭

**Comment by internelp** [comment]
我也发现了这个问题。

**Comment by tongyangsheng** [comment]
感谢各位的反馈，新版本中removeBannerAd()已经在iOS中生效，各位只需要在页面切换时手动调用一下方法即可。
