### ISSUE TITLE
头疼

### ISSUE THREAD

**Issue by autoruner** [OpenFlutter/Pangolin#41]
<img width="1394" alt="WeChat0f189265d980ddda30bec31121587544" src="https://user-images.githubusercontent.com/12791029/95111826-a6246000-0772-11eb-9789-f133e5125a31.png">

求解决

**Comment by ixugo** [comment]
使用了新的 sdk 包,  用例子里的旧包就可以了

在配置 安卓上遇到了很多问题 ,  这里我配好之前遇到的最后一个问题, 记忆深刻

另外提一下 , 有人晓得开屏广告从右侧划过来 , 背景全是黑色的, 如何处理吗?

**Comment by wengxianxun** [comment]
最近新版本我也运行不起来，退回0.2.3才行。

**Comment by tongyangsheng** [comment]
升级SDK后请使用Pangolin最新版本，穿山甲SDK和Pangolin二者版本有对应关系，不要随意切换。
