### ISSUE TITLE
Android 跑Example时出现  requesting domestic server with foreign ip

### ISSUE THREAD

**Issue by wd308389182** [OpenFlutter/Pangolin#42]
大佬，Android 运行 example时，出现下面的问题， 
requesting domestic server with foreign ip
错误码：40026
但是我的Ip是国内的，这个是什么样的问题？

IOS运行是没有问题的。 

D/AdStatsEventBatchThread(31117): clearCacheList, delete event from cache and db
D/DBMultiProviderImpl(31117): getType: content://com.tongyangsheng.pangolin_example.TTMultiProvider/t_db/ttopensdk.db/unknown/execSQL?sql=DELETE FROM logstats WHERE id IN ('ebe5c753-d90b-45a2-af9e-2231451b1b04')
D/splashLoad(31117): 广告物料预加载失败...**_.requesting domestic server with foreign ip_**40026
D/SplashAdCacheManager(31117): requesting domestic server with foreign ip40026
E/SplashAdCacheManager(31117): SplashAdCacheManager 已经加载过了 adSlot.getCodeId() 887310537
E/SplashAdCacheManager(31117): SplashAdCacheManager 是否需要加载其他rit开屏广告
E/SplashAdCacheManager(31117): entry.getKey()  887310537 entry.getValue() com.bytedance.sdk.openadsdk.component.splash.a$a$a@67c3c96
E/SplashAdCacheManager(31117): 重置开屏rit请求状态
D/AdStatsEventBatchThread(31117): start and return, checkAndDeleteEvent local size:1小于:100
D/TNCManager(31117): onResponse, url: https://api16-access-sg.pangle.io#69.192.218.33#0
D/TNCManager(31117): handleTncProbe, no probeProto, api16-access-sg.pangle.io
D/TNCManager(31117): onResponse, url matched: https://api16-access-sg.pangle.io#69.192.218.33#0 2#1#2 0#0#0
D/TNCManager(31117): onResponse, url: https://api16-access-sg.pangle.io#69.192.218.33#0
D/TNCManager(31117): handleTncProbe, no probeProto, api16-access-sg.pangle.io
D/TNCManager(31117): onResponse, url matched: https://api16-access-sg.pangle.io#69.192.218.33#0 2#1#2 0#0#0
D/TNCManager(31117): onResponse, url: https://api16-access-sg.pangle.io#69.192.218.33#0
D/TNCManager(31117): handleTncProbe, no probeProto, api16-access-sg.pangle.io
D/TNCManager(31117): onResponse, url matched: https://api16-access-sg.pangle.io#69.192.218.33#0 2#1#2 0#0#0
D/TNCManager(31117): onResponse, url: https://api16-access-sg.pangle.io#69.192.218.33#0
D/TNCManager(31117): handleTncProbe, no probeProto, api16-access-sg.pangle.io
D/TNCManager(31117): onResponse, url matched: https://api16-access-sg.pangle.io#69.192.218.33#0 2#1#2 0#0#0
D/DBMultiProviderImpl(31117): insert: content://com.tongyangsheng.pangolin_example.TTMultiProvider/t_db/ttopensdk.db/logstatsbatch
D/AdStatsEventBatchThread(31117): onHandleReceivedAdEvent mCloseSaveAndRetry is false, save event into db
D/AdStatsEventBatchThread(31117): onHandleReceivedAdEvent

**Comment by tongyangsheng** [comment]
我之前遇到过一次类似问题，但是无法复现，我猜测是穿山甲SDK本身会有一些网络缓存机制，导致之前你有翻过墙会检测到你是国外ip，我出现一次以后真机重新运行就正常了。首先排除是插件的问题，可以去穿山甲官网创建工单咨询，他们的服务态度不错的，回复很快😄 ，如果他们那边有什么解决方案欢迎继续写到这个issue里，谢谢

**Comment by wd308389182** [comment]
好的，我自己试一下。 谢谢大佬解答。

**Comment by wd308389182** [comment]
@tongyangsheng  大佬，你说的真机重新运行，指的是手机重新启动吗？

**Comment by tongyangsheng** [comment]
我之前出现这个问题是在模拟器上，我在真机上没有出现相关问题。你可以项目删了重新跑一下试试

**Comment by wd308389182** [comment]
好的，我还是提交工单吧， 我已经重新安装了，还是出现这种问题。 谢谢你的回复。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "多肉葡萄"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 下午2:59
收件人: "OpenFlutter/Pangolin"<Pangolin@noreply.github.com&gt;; 
抄送: "③ ㈡ ⒈"<308389182@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/Pangolin] Android 跑Example时出现  requesting domestic server with foreign ip (#42)





 
我之前出现这个问题是在模拟器上，我在真机上没有出现相关问题。你可以项目删了重新跑一下试试
