### ISSUE TITLE
希望能加入QQ交流群

### ISSUE THREAD

**Issue by wd308389182** [OpenFlutter/Pangolin#43]
大佬，能把QQ群发我下吗？谢谢！！！

**Comment by JarvanMo** [comment]
可以来OpenFlutter的群哦，892398530

**Comment by wd308389182** [comment]
谢谢啦。&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JarvanMo"<notifications@github.com&gt;; 
发送时间: 2020年10月29日(星期四) 下午4:54
收件人: "OpenFlutter/Pangolin"<Pangolin@noreply.github.com&gt;; 
抄送: "③ ㈡ ⒈"<308389182@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/Pangolin] 希望能加入QQ交流群 (#43)





 
可以来OpenFlutter的群哦，892398530

**Comment by tongyangsheng** [comment]
直接加莫老的群吧，我也在群里，我没有建QQ群，id:多肉葡萄
