### ISSUE TITLE
开屏广告动画背景黑屏

### ISSUE THREAD

**Issue by ixugo** [OpenFlutter/Pangolin#44]
开屏广告动画背景黑屏
###  问题描述
我认为此问题非 #3 , #27 等问题
如图所示 , 该问题是从右侧滑动过来的开屏广告 , 背景是黑色的?
可以去掉这个滑动动画吗 ?  直接展示

### Pangolin 版本
0.2.4

### Flutter 版本
1.23

### 问题出现的平台
仅安卓!   ios 没有任何问题

### 问题的初现频率
100%

![2020-10-30 18 07 05](https://user-images.githubusercontent.com/59127546/97692541-dd203400-1ada-11eb-8919-0da8de2b869e.gif)

**Comment by tongyangsheng** [comment]
这个背景是可以自己设置颜色的，因为这个插件中不是直接返回一个nativeView，所以你看到的黑屏其实是Android自带的一个启动页。针对Flutter项目在Android上的启动相关问题，可以参考[如何处理Flutter在Android上的启动](https://flutter.cn/docs/development/add-to-app/android/add-splash-screen)。正常的App包括启动页和闪屏页，我对穿山甲中的splashAd的理解更像一个闪屏页而不是启动页。

**Comment by ixugo** [comment]
> 背景是可以自己设置颜色的，因为这个插件中不是直接返回一个nativeView，所以你看到的黑屏其实是Android自带的一个启动页。针对Flutter项目在Android上的启动相关问题，可以参

非常感谢你帮我解决问题 , 暂时项目放弃增加广告, 后面我会尝试
