### ISSUE TITLE
android 激励视频，关闭debug 没回调

### ISSUE THREAD

**Issue by tangbincheng** [OpenFlutter/Pangolin#47]
作者代码写错了，RawardVideo 里面onAdClose 方法错误
正确写法在一下，就是修改了debug方法结尾的括号位置
 @Override
                    public void onAdClose() {
                        if (debug)
                        {
                            TToast.show(context, "rewardVideoAd close");
                         }
                         Map<String,Object> rewardVideoCallBack = new HashMap<>();
                            rewardVideoCallBack.put("rewardVerify",false);
                            rewardVideoCallBack.put("rewardAmount", 0);
                            rewardVideoCallBack.put("rewardName","rewardVideo Close");
                            _channel.invokeMethod("onRewardResponse",rewardVideoCallBack);
                    }

**Comment by tongyangsheng** [comment]
nice! 解决了大问题！ thank you
