### ISSUE TITLE
0.2.5最新版对flutter好像运行不起来？

### ISSUE THREAD

**Issue by wengxianxun** [OpenFlutter/Pangolin#48]
* Where:
Build file '/Users/wengxianxun/.pub-cache/hosted/pub.flutter-io.cn/pangolin-0.2.5/android/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':pangolin'.
> Project with path ':open_ad_sdk_new' could not be found in project ':pangolin'.

**Comment by wengxianxun** [comment]
我回退到0.2.3版本就可以运行

**Comment by muyu2019** [comment]
'/Users/wengxianxun/.pub-cache/hosted/pub.flutter-io.cn/pangolin-0.2.5/android/build.gradle' line: 37
找到这个文件，定位到37行代码。看看写的是什么。
```
implementation project(path: ':open_ad_sdk_new')
```
需要在android目录下复制open_ad_sdk一份为open_ad_sdk_new，同时settings.grade文件需要改动 include ':open_ad_sdk_new'

我是进行到这里了，不过依然在报新的问题的错误。

参考文档去做没有跑起来，同时还需要参考example下面的代码。

**Comment by tongyangsheng** [comment]
更新到 0.2.7 试试，之前有一个重大bug，没有适配低版本

**Comment by pomin** [comment]
还是报错了

**Comment by tongyangsheng** [comment]
我自己重新建了一个flutter_demo 导入Pangolin并按照文档进行相关配置后，测试一切功能正常。各位遇到的问题大部分是自己的配置原因，或者与其他插件存在冲突。作为开发者需要具备基本的两个原则：细心和钻研。针对个人接入的流程我一会将完善文档，由于本issue内均为提供有效报错信息，所以关闭issue，请各位按照文档检查配置，遇到相关问题，参考issue 格式提出issue，方便我排查问题，其余issue将不予回复，敬请谅解🤯

**Comment by luokunman** [comment]
> 我自己重新建了一个flutter_demo 导入Pangolin并按照文档进行相关配置后，测试一切功能正常。各位遇到的问题大部分是自己的配置原因，或者与其他插件存在冲突。作为开发者需要具备基本的两个原则：细心和钻研。针对个人接入的流程我一会将完善文档，由于本issue内均为提供有效报错信息，所以关闭issue，请各位按照文档检查配置，遇到相关问题，参考issue 格式提出issue，方便我排查问题，其余issue将不予回复，敬请谅解🤯

我更新到0.2.7依然好像不太行。  其余配置参考了穿山甲的配置 
似乎是 Build file 'C:\Users\admin\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\pangolin-0.2.7\android\build.gradle' line: 39
即是 implementation project(path: ':open_ad_sdk')这个问题的错   是否应该更正为implementation 'com.pangle.cn:ads-sdk:3.5.0.6'
