### ISSUE TITLE
ios build失败

### ISSUE THREAD

**Issue by gityan** [OpenFlutter/Pangolin#5]
Failed to build iOS app
Error output from Xcode build:
↳
    2020-04-17 17:08:27.710 xcodebuild[34506:6310258]  DTDeviceKit: deviceType from dddaf37ad2da4c140fe193912b6502cfdb09ce3c was NULL
    2020-04-17 17:08:27.838 xcodebuild[34506:6310257]  DTDeviceKit: deviceType from dddaf37ad2da4c140fe193912b6502cfdb09ce3c was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/yanzh/Downloads/Pangolin-master/ios/Classes/PangolinPlugin.m:1:
    /Users/yanzh/Downloads/Pangolin-master/ios/Classes/PangolinPlugin.h:5:34: error: no type or protocol named 'BUDExampleViewModel'
    @property (nonatomic, strong) id<BUDExampleViewModel> viewModel;
                                     ^
    /Users/yanzh/Downloads/Pangolin-master/ios/Classes/PangolinPlugin.m:40:29: warning: assigning to 'id<BUSplashAdDelegate> _Nullable' from incompatible type 'PangolinPlugin *const __strong'
            splashView.delegate = self;
                                ^ ~~~~
    1 warning and 1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'Runner' from project 'Runner')

0.0.7版本

**Comment by tongyangsheng** [comment]
最近一直在搞激励视频 影响到了开屏的部分代码 马上更新到v0.0.8 还有问题我会继续跟进
