### ISSUE TITLE
null safe

### ISSUE THREAD

**Issue by liu2080019** [OpenFlutter/Pangolin#58]
有时候考虑改造下null safe的支持吗

**Comment by yy1300326388** [comment]
@liu2080019 

我使用这个插件[flutter_pangle_ads](https://github.com/FlutterAds/flutter_pangle_ads) 支持空安全，非常不错
![image](https://user-images.githubusercontent.com/8764899/131304616-4bdd5942-58dc-4bdf-93f1-56058d274749.png)

**Comment by yy1300326388** [comment]
@liu2080019 我使用flutter pangle ads

**Comment by yy1300326388** [comment]
评论了好几次都被删除，其实好不好看看源码即可

**Comment by tongyangsheng** [comment]
@yy1300326388 同意，但是你在我的博客，知乎，github全面多次，恶意的刷评论已经引起了我的反感。麻烦远离

**Comment by tongyangsheng** [comment]
test
